runtime: python27
api_version: 1
threadsafe: true

builtins:
# Deferred is required to use google.appengine.ext.deferred.
# This is used to update the datastore model schema
# Used by the UpdateSchemaHandler() class in main.py
- deferred: on

handlers:
- url: /static
  static_dir: static

- url: /www/img
  static_dir: www/img

- url: /www/icons
  static_dir: www/icons

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

# - url: /update_schema
#   script: main.app
#   login: admin
#   secure: always

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"
