runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /www/img
  static_dir: www/img

- url: /www/icons
  static_dir: www/icons

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
